sudo: false
language: node_js
node_js:
  - "node"
  - "9"
  - "8"
script:
  - npm coverage
  - npm run build && npm run test:chrome
after_success: npm run coverage
cache: npm
addons:
  chrome: stable
